'update or insert into PREVENDA'
   '(Cod_Filial, Codigo, '
   'cod_vendedor, Nota, Cod_Transacao,  '
   'CODPREVENDA,  Tipo_Operacao, '
   'CFOP, Serie, Modelo, '
   'Base_ICMS, Valor_ICMS, Base_ICMSST,'
   ' Valor_ICMSST, Total_Produtos,'
   'Valor_Frete, Valor_Seguro, Desconto, '
   'Outras_Despesas, Valor_IPI,'
   'Valor_PIS, Valor_Cofins,'
   'Total_Final, Valor_Financeira, ModFrete,'
   'Data_Emissao, Data_Entrega, Emitente,'
   ' Finalidade, Situacao)'
   'values (' + codigo da filial que ta logado + ' , '
 codigo do usuario que ta logado + ' , '
   Codigo do usuario que tá logado+ ' , '
 null+ ' , '
   null + ','
  'GEN_ID(GEN_TRANSACAO_PREVENDA,1),'
   0 + ','
   '' + ','
      '' + ','
   '' + ','
   0 + ', '
   0 + ', '
   0+ ', '
   0 + ', '
   0 + ', '
   0+ ', '
   0 + ', '
   0+ ', '
   0+ ', '
 0 + ', '
   0 + ', '
   0 + ', '
  0 + ', '
 0 + ', '
   0 + ', '
  + 'CURRENT_DATE , '
    + ' CURRENT_DATE, '
  + '1 , '
  + '1 , ''N)'